### ISSUE TITLE
return code of downloader is 0 although files were not loaded completely

### ISSUE THREAD

**Issue by JJ-Author** [dbpedia/Dockerized-DBpedia#17]
```
store_1     | 19:31:32 HTTP/WebDAV server online at 8890
store_1     | 19:31:32 Server online at 1111 (pid 1)
download_1  | File saved to /root/data/mappingbased-literals_lang=en.ttl.bz2
download_1  | Downloading file: https://downloads.dbpedia.org/repo/lts/mappings/geo-coordinates-mappingbased/2019.09.01/geo-coordinates-mappingbased_lang=en.ttl.bz2
download_1  | File saved to /root/data/geo-coordinates-mappingbased_lang=en.ttl.bz2
download_1  | Downloading file: https://raw.githubusercontent.com/dbpedia/ontology-tracker/master/databus/dbpedia/ontology/dbo-snapshots/2019.02.21T08.00.00Z/dbo-snapshots.nt
download_1  | java.io.FileNotFoundException: https://raw.githubusercontent.com/dbpedia/ontology-tracker/master/databus/dbpedia/ontology/dbo-snapshots/2019.02.21T08.00.00Z/dbo-snapshots.nt
download_1  |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1896)
download_1  |   at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
download_1  |   at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
download_1  |   at java.net.URL.openStream(URL.java:1067)
download_1  |   at org.dbpedia.download.Client.main(Client.java:129)
download_1  | Removing LOCK at /root/data
dockerized-dbpedia_download_1 exited with code 0
load_1      | will use ISQL port 1111 to connect
load_1      | [INFO] Waiting for store to come online (s)
```

**Comment by holycrab13** [comment]
What is the desired behaviour? Cancel execution when a file doesn't exist?

**Comment by JJ-Author** [comment]
it is good that it does not crash but we should return another code instead and might also show some promiment warning at the end of the loader script.
