### ISSUE TITLE
Not working with new Databus collections? 

### ISSUE THREAD

**Issue by manonthegithub** [dbpedia/Dockerized-DBpedia#31]
Tried with https://databus.dbpedia.org/kikiriki/collections/test_deployment

getting
```
virtuoso-sparql-endpoint-quickstart-download-1  | Loading collection https://databus.dbpedia.org/kikiriki/collections/test_deployment
virtuoso-sparql-endpoint-quickstart-download-1  | GET: https://databus.dbpedia.org/kikiriki/collections/test_deployment / ACCEPT: text/sparql
virtuoso-sparql-endpoint-quickstart-store-1     | 15:25:30 Checkpoint started
virtuoso-sparql-endpoint-quickstart-store-1     | 15:25:30 Checkpoint finished.
virtuoso-sparql-endpoint-quickstart-store-1     | 15:25:30 Roll forward started
virtuoso-sparql-endpoint-quickstart-store-1     | 15:25:30 Roll forward complete
virtuoso-sparql-endpoint-quickstart-download-1  | Collections resolved to query:
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX dcat:   <http://www.w3.org/ns/dcat#>
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX dct:    <http://purl.org/dc/terms/>
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX dcv: <https://dataid.dbpedia.org/databus-cv#>
virtuoso-sparql-endpoint-quickstart-download-1  | PREFIX databus: <https://dataid.dbpedia.org/databus#>
virtuoso-sparql-endpoint-quickstart-download-1  | SELECT ?file WHERE
virtuoso-sparql-endpoint-quickstart-download-1  | {
virtuoso-sparql-endpoint-quickstart-download-1  | 	{
virtuoso-sparql-endpoint-quickstart-download-1  | 		GRAPH ?g
virtuoso-sparql-endpoint-quickstart-download-1  | 		{
virtuoso-sparql-endpoint-quickstart-download-1  | 			{
virtuoso-sparql-endpoint-quickstart-download-1  | 				?dataset databus:group <https://databus.dbpedia.org/dbpedia/generic> .
virtuoso-sparql-endpoint-quickstart-download-1  | 				{
virtuoso-sparql-endpoint-quickstart-download-1  | 				?dataset databus:artifact <https://databus.dbpedia.org/dbpedia/generic/labels> .
virtuoso-sparql-endpoint-quickstart-download-1  | 				{ ?distribution <https://dataid.dbpedia.org/databus-cv#lang> 'bug' . }
virtuoso-sparql-endpoint-quickstart-download-1  | 				{ ?distribution <http://purl.org/dc/terms/hasVersion> '2021.02.01' . }
virtuoso-sparql-endpoint-quickstart-download-1  | 				}
virtuoso-sparql-endpoint-quickstart-download-1  | 			}
virtuoso-sparql-endpoint-quickstart-download-1  | 			?dataset dcat:distribution ?distribution .
virtuoso-sparql-endpoint-quickstart-download-1  | 			?distribution databus:file ?file .
virtuoso-sparql-endpoint-quickstart-download-1  | 		}
virtuoso-sparql-endpoint-quickstart-download-1  | 	}
virtuoso-sparql-endpoint-quickstart-download-1  | }
virtuoso-sparql-endpoint-quickstart-download-1  | 
virtuoso-sparql-endpoint-quickstart-download-1  | CHECKING FOR URLENCODED
virtuoso-sparql-endpoint-quickstart-download-1  | RESULT: false
virtuoso-sparql-endpoint-quickstart-download-1  | Exception in thread "main" org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
virtuoso-sparql-endpoint-quickstart-download-1  | 	at org.json.JSONTokener.syntaxError(JSONTokener.java:505)
virtuoso-sparql-endpoint-quickstart-download-1  | 	at org.json.JSONObject.<init>(JSONObject.java:215)
virtuoso-sparql-endpoint-quickstart-download-1  | 	at org.json.JSONObject.<init>(JSONObject.java:399)
virtuoso-sparql-endpoint-quickstart-download-1  | 	at org.dbpedia.download.Client.main(Client.java:138)
virtuoso-sparql-endpoint-quickstart-download-1  | Removing LOCK at /root/data
virtuoso-sparql-endpoint-quickstart-download-1 exited with code 0
```

**Comment by manonthegithub** [comment]
See no data from the file in the collection performing query:
```
select distinct ?s ?o where {?s <http://www.w3.org/2000/01/rdf-schema#label> ?o}
```

**Comment by kurzum** [comment]
Collections seems to work: 
```
query=$(curl -H "Accept:text/sparql" https://databus.dbpedia.org/kikiriki/collections/test_deployment)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   777  100   777    0     0   4589      0 --:--:-- --:--:-- --:--:--  4597
kurzum@lat:/tmp$ curl -X POST -H "Accept: text/csv" --data-urlencode "query=${query}" https://databus.dbpedia.org/sparql
"file"
"https://databus.dbpedia.org/dbpedia/generic/labels/2021.02.01/labels_lang=bug.ttl.bzip2"
```

The error seems to be in https://github.com/dbpedia/dbpedia-databus-collection-downloader

**Comment by manonthegithub** [comment]
quick fix:
```shell
COLLECTION_URI=https://databus.dbpedia.org/kikiriki/collections/ldk2023test SPARQL_ENDPOINT=https://databus.dbpedia.org/sparql VIRTUOSO_ADMIN_PASSWD=YourSecretPassword docker-compose up
```
